# Generated by Django 4.1.1 on 2022-09-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('BF', 'Breakfast'), ('LU', 'Lunch'), ('DN', 'Dinner'), ('DE', 'Dessert'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
