# Generated by Django 4.1.1 on 2022-09-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_dish_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
    ]
